#!/bin/bash

NMAX=5
path[0]=/home/seriy/Music/other/gameOfThronesOstM.mp3
path[1]=/home/seriy/Music/other/gameOfThronesOst.mp3
path[2]=/home/seriy/Music/nemo.mp3
path[3]=/home/seriy/Music/dwUtah.mp3
path[4]=/home/seriy/Music/wt.mp3

if [ "X$1" == "Xcheck" ]
then
    i=0
    while (( $i < $NMAX ))
    do
        if [ -f "${path[$i]}" ]
        then
            echo "File $i ${path[$i]} exists"
        else
            echo "File $i ${path[$i]} DOESNT EXIST"
        fi
        let i=i+1
    done
    exit
fi

if [ "X$1" != "X" ]
then
    /usr/bin/mplayer "${path[$1]}"
    exit
fi

boinccmd --set_run_mode never

sleep 10

N=$(echo "$RANDOM % $NMAX" | bc)

file=${path[$N]}

echo $N $file

logger -t Alarm "Using file #$N $file"
pacmd set-sink-port 0 analog-output-speaker
pacmd set-sink-mute 0 0
pacmd set-sink-volume 0 0x20000

/usr/bin/mplayer "$file"&

sleep 5

for sink in $(pacmd list-sink-inputs|grep -aEo "index: [0-9]+"|grep -aEo "[0-9]+")
do
    pacmd set-sink-input-mute $sink 0
    pacmd set-sink-input-volume $sink 0x15000
done
