#!/bin/bash

NMAX=5
path[0]=/home/seriy/Music/other/gameOfThronesOstM.mp3
path[1]=/home/seriy/Music/other/gameOfThronesOst.mp3
path[2]=/home/seriy/Music/nemo.mp3
path[3]=/home/seriy/Music/dwUtah.mp3
path[4]=/home/seriy/Music/wt.mp3

if [ "X$1" == "Xcheck" ]
then
    i=0
    while (( $i < $NMAX ))
    do
        if [ -f "${path[$i]}" ]
        then
            echo "File $i ${path[$i]} exists"
        else
            echo "File $i ${path[$i]} DOESNT EXIST"
        fi
        let i=i+1
    done
    exit
fi

if [ "X$1" != "X" ]
then
    /usr/bin/vlc "${path[$1]}"
    exit
fi

killall -9 vlc
boinccmd --set_run_mode never
killall -9 vlc

sleep 10

N=$(echo "$RANDOM % $NMAX" | bc)

file=${path[$N]}

echo $N $file

card=1
logger -t Alarm "Using file #$N $file"
PACMD="pacmd"
export PULSE_RUNTIME_PATH=/run/user/1000/pulse
$PACMD set-sink-port $card analog-output-speaker
$PACMD set-sink-mute $card 0
$PACMD set-sink-volume $card 0x20000

/usr/bin/vlc -I dummy --aout pulse --ignore-config --volume 512 "$file"&

sleep 5

for sink in $(pacmd list-sink-inputs|grep -aEo "index: [0-9]+"|grep -aEo "[0-9]+")
do
    $PACMD set-sink-input-mute $sink 0
    $PACMD set-sink-input-volume $sink 0x15000
done
