#!/bin/bash

ID=6635849
#ID=13851574
sleepTimeS=5

function isOffline()
{
    wget -q -O - "http://vk.com/id${ID}"|iconv -f windows-1251|grep -E "(заходил|last seen)"|wc -l
}

r=$(isOffline)
sleep $sleepTimeS

while true
do
    r1=$(isOffline)
    echo "offline: was $r now $r1"
    if [ "X$r" != "X$r1" ]
    then
        echo "    State changed!"
        $INF_PATH/alarm
    fi
    r=$r1
    sleep $sleepTimeS
done
