######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 6 21:28:51 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += ../src
INCLUDEPATH += ../src

# Input
SOURCES += main.c
