######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 4 15:06:19 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += check.cpp
