######################################################################
# Automatically generated by qmake (2.01a) Fri Nov 22 22:00:07 2013
######################################################################

TEMPLATE = app
TARGET = controller
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += common.h
SOURCES += common.c controller.c multicast.c
