######################################################################
# Automatically generated by qmake (2.01a) Fri Nov 22 22:00:07 2013
######################################################################

TEMPLATE = app
TARGET = starter
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += common.h \
    multicast.h \
    parseargs.h \
    myauth.h
SOURCES += common.c multicast.c starter.c \
    parseargs.c \
    myauth.c
