######################################################################
# Automatically generated by qmake (2.01a) Fri Nov 22 19:37:04 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += common.h mmapped.h msgqueue.h sems.h
SOURCES += client.c common.c mmapped.c msgqueue.c sems.c server.c
