######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 18 18:34:32 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
