######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 6 18:10:36 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main1.cpp
