######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 11 21:01:52 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
