######################################################################
# Automatically generated by qmake (2.01a) Fri Nov 22 19:37:04 2013
######################################################################

TEMPLATE = app
TARGET = server
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mmapped.h common.h msgqueue.h sems.h
SOURCES += mmapped.c common.c msgqueue.c sems.c server.c
