######################################################################
# Automatically generated by qmake (2.01a) Fri Nov 22 19:37:04 2013
######################################################################

TEMPLATE = app
TARGET = client
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += common.h sems.h
SOURCES += common.c client.c sems.c
