#!/bin/bash
tc=1
tMax=4

i=0
rM=3

N=50000

name=04_vertexNum

while (( $tc <= $tMax ))
do
    i=0
    while (( $i <= $rM ))
    do
        ./$name random $N | /usr/bin/time -o f1 -f "%e" ./$name test $tc > /dev/null
        echo "$i $(cat f1)"
        let i=i+1
    done
    let tc=tc+1
done
