######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 4 14:58:18 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
