######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 16 17:49:59 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
